apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - prometheus-config.yaml
  - prometheus-statefulset.yaml
  - alertmanager.yaml
  - exporters.yaml
configMapGenerator:
  - name: prometheus-config
    namespace: infra
    files:
      - prometheus.yml=prometheus.yaml
